language: go
go:
  - "1.13.x"

env:
  - GO111MODULE=on

script:
  - export GOROOT=$(go env GOROOT)
  - if [ -n "$(gofmt -l .)" ]; then
      echo "Go code is not formatted:"; gofmt -d .; exit 1;
    fi
  - go test ./storage
  - go test -race -short ./storage
